Parameter transition from block device to LittleFS
This can be reverted after the transition period

diff --git a/ROMFS/px4fmu_common/init.d/rcS b/ROMFS/px4fmu_common/init.d/rcS
--- a/ROMFS/px4fmu_common/init.d/rcS
+++ b/ROMFS/px4fmu_common/init.d/rcS
@@ -126,6 +126,18 @@ else
 	if mft query -q -k MTD -s MTD_PARAMETERS -v /fs/mtd_params
 	then
 		set PARAM_FILE /fs/mtd_params/parameters.bson
+	else
+		# Revert after the transition period is completed
+		set PARAM_FILE /fs/mtd_params/parameters.bson
+		param select $PARAM_FILE
+		echo "Start parameter transition to LittleFS"
+		if ! param transition
+		then
+			echo "ERROR [init] param transition"
+		else
+			echo "Successful param transition. The system will reboot!"
+			reboot
+		fi
 	fi
 
 	#
